//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLawyer.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using MyLawyer.Entities;
    
    public partial class MyLawyerPublicEntities : DbContext
    {
        public MyLawyerPublicEntities()
            : base("name=MyLawyerPublicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Keyword> Keywords { get; set; }
        public DbSet<LawBar> LawBars { get; set; }
        public DbSet<LawSector> LawSectors { get; set; }
        public DbSet<Lawyer> Lawyers { get; set; }
        public DbSet<MainSector> MainSectors { get; set; }
        public DbSet<Membership> Memberships { get; set; }
        public DbSet<Study> Studies { get; set; }
        public DbSet<LinkMetaData> LinkMetaData { get; set; }
    }
}
