//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyLawyer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LawSector
    {
        public LawSector()
        {
            this.Keywords = new HashSet<Keyword>();
            this.Lawyers = new HashSet<Lawyer>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
        public Nullable<int> MainSectorId { get; set; }
    
        public virtual MainSector MainSector { get; set; }
        public virtual ICollection<Keyword> Keywords { get; set; }
        public virtual ICollection<Lawyer> Lawyers { get; set; }
    }
}
