//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lawyers
    {
        public Lawyers()
        {
            this.Membership = new HashSet<Membership>();
            this.Keywords = new HashSet<Keywords>();
            this.LawSectors = new HashSet<LawSectors>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string PrimaryPhone { get; set; }
        public string Email { get; set; }
        public int LawBarId { get; set; }
        public string RegistrationYear { get; set; }
        public string SecondaryPhone { get; set; }
        public string Fax { get; set; }
        public Nullable<int> StudiesId { get; set; }
        public string Website { get; set; }
        public string Description { get; set; }
        public string LogoUrl { get; set; }
        public string Url { get; set; }
        public byte[] RegistrationTimeStamp { get; set; }
    
        public virtual LawBars LawBars { get; set; }
        public virtual Studies Studies { get; set; }
        public virtual ICollection<Membership> Membership { get; set; }
        public virtual ICollection<Keywords> Keywords { get; set; }
        public virtual ICollection<LawSectors> LawSectors { get; set; }
    }
}
