//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membership
    {
        public int Id { get; set; }
        public int Membership1 { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public int PaymentMethod { get; set; }
        public int LawyerId { get; set; }
    
        public virtual Lawyers Lawyers { get; set; }
    }
}
